services:
  - type: web
    name: ishika-chatbot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python -m ishika
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: BOT_USERNAME
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: GEMINI_API_KEY
        sync: false
